/**
 * Writes docs/partner-api/INTEGRATION_BRIEF.md from the same generator the
 * in-app integration guide uses, with placeholders instead of a partner's
 * identifiers. Run: npm run docs:integration-brief
 */
import { writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { buildIntegrationBrief, PLACEHOLDER_INPUT } from '../src/features/integration/integrationBrief';

const header = `<!-- Generated by scripts/generate-integration-brief.ts — do not edit by hand.
     Partners get this with their own identifiers filled in from the app's
     "Connect Your System" page. -->

`;
const here = dirname(fileURLToPath(import.meta.url));
writeFileSync(resolve(here, '../docs/partner-api/INTEGRATION_BRIEF.md'), header + buildIntegrationBrief(PLACEHOLDER_INPUT));
console.log('Wrote docs/partner-api/INTEGRATION_BRIEF.md');
